name: geo_attendance_system
description: Major Project
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  splashscreen: any
  flutter_sparkline: any
  flutter_staggered_grid_view: any
  calendarro: ^1.0.0
  firebase_auth: ^4.1.0
  flutter_screenutil: ^5.6.0
  table_calendar: ^3.0.7
  firebase_database: ^10.0.3
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  flutter_spinkit: ^5.1.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
  grouped_buttons: ^1.0.3
  permission_handler: ^10.2.0
  device_info_plus: ^8.0.0
  android_id: ^0.1.3
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^12.0.3
  easy_geofencing: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/gif/loading-gif.gif
    - assets/gif/tick.gif
    - assets/gif/close.gif
    - assets/gif/no_entry.gif
    - assets/logo/logo.png
    - assets/back.jpg
    - assets/logo/logo-white.png
    - assets/logo/profile.jpg
  
  fonts:

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf

    - family: Sansation-Bold
      fonts:
        - asset: assets/fonts/Sansation-Bold.ttf

    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Bold.ttf
        - asset: assets/fonts/Bitter-Regular.ttf


